spring:
  application:
    name: taskforge

  datasource:
    url: jdbc:postgresql://localhost:5432/taskforge
    username: appuser
    password: apppass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  profiles:
    active: jpa

server:
  port: 8080
